Fix: libertyRoot not honored (libertyStart FAILED)
Encounter the following error during build when libertRoot is configured
in gradle.properties
...
> Task :daytrader-ee7:libertyStart FAILED
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':daytrader-ee7:libertyStart'.
> CWWKM2004E: When installDir is set, it must point to a directory that
contains lib/ws-launch.jar.
...
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task
':daytrader-ee7:libertyStart'.
at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
at
org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
...
Caused by: : CWWKM2004E: When installDir is set, it must point to a
directory that contains lib/ws-launch.jar.
at
net.wasdev.wlp.ant.AbstractTask.initTask(AbstractTask.java:80)
at
net.wasdev.wlp.ant.ServerTask.initTask(ServerTask.java:64)
at
net.wasdev.wlp.ant.ServerTask.execute(ServerTask.java:85)
at
org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
...